master_bedroom_night_fan:
  alias: Master Bedroom Night Fan
  icon: mdi:fan
  sequence:
    - condition: state
      entity_id: fan.master_bedroom_ceiling_fan
      state: "off"
    - variables:
        temp: "{{ states('sensor.master_bedroom_smartsensor_temperature') | float(70) }}"
    - action: fan.set_percentage
      target:
        entity_id: fan.master_bedroom_ceiling_fan
      data:
        percentage: "{{ 100 if temp > 71 else 75 }}"
