enable_thermostat_away:
  alias: Enable Thermostat Away
  icon: mdi:thermostat
  sequence:
    - action: climate.set_preset_mode
      target:
        entity_id:
          - climate.main_floor
          - climate.upstairs
      data:
        preset_mode: away

enable_thermostat_sleep:
  alias: Enable Thermostat Sleep
  icon: mdi:sleep
  sequence:
    - action: climate.set_preset_mode
      target:
        entity_id:
          - climate.main_floor
          - climate.upstairs
      data:
        preset_mode: sleep

resume_thermostat_programming:
  alias: Resume Thermostat Programming
  icon: mdi:thermostat-auto
  sequence:
    - if:
        - condition: state
          entity_id: input_boolean.guest_override
          state: "on"
      then:
        - action: ecobee.resume_program
          target:
            entity_id:
              - climate.main_floor
              - climate.upstairs
      else:
        - action: ecobee.resume_program
          target:
            entity_id:
              - climate.basement
              - climate.main_floor
              - climate.upstairs
