- id: schedule_vacation_blinds
  alias: Vacation Mode - Open Blinds
  trigger:
    - trigger: time
      at: "10:00:00"
    - trigger: time
      at: "20:00:00"
  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: "on"
  action:
    - action: script.turn_on
      target:
        entity_id: script.open_blinds
