latitude: ENC[AES256_GCM,data:cOzw1y3xA8z6,iv:zSo2OgUh3Eu6HUAmHR8yo28D1Af9WIJwhHRaxhROh0M=,tag:csNi2FiSmVTB419x4XVtIA==,type:float]
longitude: ENC[AES256_GCM,data:M6nTyUHZGbhXWg==,iv:D58UZllMYMJz8HHRZzbo+G11nkzX4woJCRoQeYAgfko=,tag:4rLfrrLEuERufEbXrJPaZg==,type:float]
elevation: ENC[AES256_GCM,data:7ATz,iv:8rLcNGbVTjq65/at1bVDqvuQMLmc+MK1e+szdtNDVog=,tag:IPEQIMGfidfke/zSWqZy2g==,type:int]
timezone: ENC[AES256_GCM,data:5k7dQLO73HkPp6TNFVHtfQ==,iv:F/jLo3qfj8ft4oIh1+XqrHF3wI10CwXu8CavJVKsgkg=,tag:8MnTmsyHAOUkkqpdxoZfeg==,type:str]
alarm_pin: ENC[AES256_GCM,data:XOtwQA==,iv:TS2U153p19oQ3/Fv6W22aKfm3ZLwzdI3Ird/iN35Btg=,tag:fRQFoXohxzFsW3xNlhS3tg==,type:str]
mqtt_user: ENC[AES256_GCM,data:rpD9FG4OUrJB,iv:MhM8drSuvSIS+KecpzyL8Nx2cjSm4ECi/2SPSft/3I0=,tag:+6713kNvBpsPTnxFxzS9sw==,type:str]
mqtt_password: ENC[AES256_GCM,data:507kp9r0B28tvo3/s1TE8Q==,iv:rOrz7wdc/G5DzVKCLWWjm7MuTHC8z7bWduryNwLB+ok=,tag:hkxFltmv19vWLgsuvxgwOA==,type:str]
healthcheck_ping_url: ENC[AES256_GCM,data:uAFth4AJBUqimmYrjCb2bCISQDfRnX5st7POMOa41WzsL/SzTHoIlPW02TjIhIWU62HiK6d8rEk=,iv:HQOT7252D5vxsAryXN7bTCsharqS0+h9/BpkKVgqJ+g=,tag:lsGY7M0ivV1Eha3uIqTv/w==,type:str]
ntfy_url: ENC[AES256_GCM,data:Uw9UJMsZGYZvHIwJ0Y4Igx2mqWxqQEylDWdDb+7QyrBNbEb1,iv:ZLBx0rx8/HNlO+we9ZD0rUxYrkK/r0VnXGYI/QF0DAE=,tag:g2syr/jetNxjcO0hYimDFw==,type:str]
tailscale_webhook_id: ENC[AES256_GCM,data:G/K10CRl5VNXeyupbIrrIaDBrlA/O7X+WwXKsG47Lrk=,iv:jGtAW2ScCixm/p3q5vO0mqvUlGt/KFfldeJgvAXAG7k=,tag:3d8CGRKx8xKFw871iX7exw==,type:str]
ntfy_token: ENC[AES256_GCM,data:dLwHDvUGAKlwoD81L1cU7MEPPRy4YrB7dUASirtVub1qNWH3etZO,iv:NSzonPvw/NBZWQPa4IBcdkMYeDMhmpNSxjzsyD60gR8=,tag:KjIxVKbBL8bdrhjVJ9g6ZA==,type:str]
sops:
    age:
        - recipient: age1knwqsjn4pf8fq93dqvnhehm3m22q8zdhxq8vwf5dtzf6a8dpm9fs4q32wx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnblZwMVRNZ1RGN2FNRUts
            RlAxK21LVlIvcGF3eS9ZL3I1VmZORVZ6MmdNCi9BUGo3dlZqVmhCbHMrTnZOTStJ
            UDZmdmRNL3JxOW91ZkhDVTVwOHNzMU0KLS0tIHFCejJwYnkrcDVHWnhqSzBrZUdH
            UnQvOXFHNDB4Q0paNml6Q1hqWVlOT1EK68m2od2G3Hyhz6Cx+KG+J41wN2u6hyNO
            p4EUona+znRnrMyn7ywcK8vIHGTn1p1qJ/FxozVHqlIit8KCKtvuIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-13T19:22:08Z"
    mac: ENC[AES256_GCM,data:LgLHWEHWOkIMlraWB/O8R8VDhpnLD44+CO/+yaylR2SeA6yXQqdvmFXqrFlkUZnkHbeOgRWG6jjG1kee8zyl72+zRQrdzRUWEoI/k6aU6Q/uBwGIB3noCNYrnRt2q57rTAiRzbMTAwb8U9FvH655AD9KXT4/0Qi9JesP517hgyY=,iv:LrVkT308vmDm3NnH6ujHfXzVI+PcESeJJXM58DyZOGQ=,tag:XSi3DwhW/9i6x9BI/lWbTw==,type:str]
    encrypted_regex: ^(password|token|api_key|secret|alarm_pin|latitude|longitude|elevation|timezone|mqtt_user|mqtt_password|healthcheck_ping_url|ntfy_url|ntfy_token|tailscale_webhook_id)$
    version: 3.10.2
