- id: misc_guest_mode_enabled
  alias: Guest Mode - Enabled → Disarm + Thermostat
  mode: single
  trigger:
    - trigger: state
      entity_id: input_boolean.guest_override
      to: "on"
  action:
    - action: script.turn_on
      target:
        entity_id: script.disarm
    - action: climate.set_preset_mode
      target:
        entity_id: climate.basement
      data:
        preset_mode: sleep

- id: misc_guest_mode_24h_reminder
  alias: Guest Mode - 24h Reminder
  mode: single
  trigger:
    - trigger: state
      entity_id: input_boolean.guest_override
      to: "on"
      for:
        days: 1
  action:
    - action: notify.mobile_app_jacksons_iphone
      data:
        message: Guest Mode has been enabled for 24 hours.
        data:
          actions:
            - action: DISABLE_GUEST
              title: Disable
            - action: ACKNOWLEDGE
              title: Acknowledge
