- id: zigbee_battery_low
  alias: Zigbee Battery Low
  trigger:
    - trigger: numeric_state
      entity_id:
        - sensor.basement_stairwell_sensor_motion_01_battery
        - sensor.front_door_battery
        - sensor.front_door_sensor_magnet_battery
        - sensor.garage_door_battery
        - sensor.garage_door_sensor_magnet_battery
        - sensor.guest_bedroom_bathroom_sensor_motion_battery
        - sensor.guest_bedroom_sensor_magnet_battery
        - sensor.guest_bedroom_sensor_motion_battery
        - sensor.living_room_sensor_cube_battery
        - sensor.main_floor_stairwell_sensor_motion_01_battery
        - sensor.main_floor_stairwell_sensor_motion_02_battery
        - sensor.master_bathroom_smart_button_battery
        - sensor.master_bathroom_weather_battery
        - sensor.master_bedroom_closet_sensor_motion_battery
        - sensor.master_bedroom_sensor_magnet_battery
        - sensor.master_bedroom_sensor_motion_battery
        - sensor.master_bedroom_smart_button_battery
        - sensor.master_bedroom_smart_button_2_battery
        - sensor.office_sensor_motion_battery
        - sensor.roof_door_sensor_magnet_battery
        - sensor.pantry_door_sensor_magnet_left_battery
        - sensor.pantry_door_sensor_magnet_right_battery
      below: 20
  action:
    - action: notify.mobile_app_jacksons_iphone
      data:
        title: Zigbee Battery Low
        message: >-
          {{ trigger.to_state.name }} battery is at {{ trigger.to_state.state }}%

- id: smart_plug_unavailable
  alias: Smart Plug Unavailable
  trigger:
    - trigger: state
      entity_id:
        - switch.dining_room_smart_plug
        - switch.living_room_smart_plug
        - switch.master_bedroom_smart_plug
      to: unavailable
  action:
    - action: notify.mobile_app_jacksons_iphone
      data:
        title: Smart Plug Unavailable
        message: >-
          {{ trigger.to_state.name }} is unavailable

- id: door_sensor_unavailable
  alias: Door Sensor Unavailable
  trigger:
    - trigger: state
      entity_id:
        - binary_sensor.front_door_sensor_magnet_contact
        - binary_sensor.garage_door_sensor_magnet_contact
        - binary_sensor.guest_bedroom_sensor_magnet_contact
        - binary_sensor.main_floor_bathroom_sensor_magnet_contact
        - binary_sensor.main_floor_closet_sensor_magnet_contact
        - binary_sensor.master_bathroom_sensor_magnet_contact
        - binary_sensor.master_bedroom_sensor_magnet_contact
        - binary_sensor.office_bathroom_sensor_magnet_contact
        - binary_sensor.office_sensor_magnet_contact
        - binary_sensor.roof_door_sensor_magnet_contact
        - binary_sensor.utility_room_sensor_magnet_contact
      to: unavailable
      for:
        hours: 6
  action:
    - action: notify.mobile_app_jacksons_iphone
      data:
        title: Door Sensor Unavailable
        message: >-
          {{ trigger.to_state.name }} has been unavailable for 6 hours
